Minor: simplification of example.
bdlukaa/fluent_ui pull request #1018
Opened 2024-01-30 12:54 UTC by ignatz

I'm new to fluent_ui and as I was reading through the example I found it to be slightly harder to follow than necessary. These are my suggestions to streamline the initial exposure.

## Pre-launch Checklist

- [ ] I have updated `CHANGELOG.md` with my changes  
- [ ] I have run "dart format ." on the project  
- [ ] I have added/updated relevant documentation

2024-02-04 10:22 UTC, hunt978 commented
It took me three days to figure out how the home page works. The main issue with this demonstration is the duplicated information required by the go_router and pane_items. One possible solution is grouping navgation prompting, routing and page building together. By supplying builders for either go_router or pane_item, the reduction of total complexity could have been archive.

2024-02-04 11:38 UTC, ignatz commented
Hey @hunt978 , I did notice and appreciate that part too. That said, I didn't dare to change that part. I wasn't sure if that was maybe intentional to demonstrate the use of gorouter as a popular package :shrug:

2024-02-06 14:32 UTC, bdlukaa requested changes

2024-02-06 14:32 UTC, bdlukaa commented on example/lib/main.dart
> -      },
Why was this removed? This is important to keep the focus on the page.

2024-11-21 03:39 UTC, closed without merging