feat: Make the example work on Linux
bdlukaa/fluent_ui pull request #1129
Opened 2024-10-22 20:53 UTC by iamsergio

This makes it easier for Linux users to play with it.

It was missing the platform boilerplate.

## Pre-launch Checklist

- [x] I have updated `CHANGELOG.md` with my changes  
- [x] I have run "dart format ." on the project  
- [ ] I have added/updated relevant documentation

2024-10-23 11:54 UTC, bdlukaa requested changes

2024-10-23 11:54 UTC, bdlukaa commented on CHANGELOG.md
> +- feat: Make the example work on Linux
This doesn't need to be in the changelog

2024-10-23 22:43 UTC, bdlukaa approved these changes

2024-10-24 13:20 UTC, iamsergio commented
I've removed the `example/linux/flutter/ephemeral` directory, as that's generated automatically by the build.
Also solves the nagging about it being in .gitignore

2024-10-25 10:17 UTC, merged