Minor update of ToggleSwitch, TextBox, Checkbox styles
bdlukaa/fluent_ui pull request #117
Opened 2021-12-22 16:11 UTC by Kapranov98

In the current version ToggleSwitch, TextBox, Checkbox differ from components from Windows UI Library. I changed the styles a bit to make these elements more similar to those used in WinUI. In my opinion, it has become more beautiful 🙂
No documentation update required.

![1](https://user-images.githubusercontent.com/4894671/147121942-672294bf-92aa-4c21-96e3-19b6fb760f94.png)
![2](https://user-images.githubusercontent.com/4894671/147121946-7a0ce337-31b4-4697-b861-f42166cbfc51.png)

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files  
- [x] I have updated `CHANGELOG.md` with my changes  
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could
- [x] I have added/updated relevant documentation
- [x] I have run `flutter pub publish --dry-run` and addressed any warnings

2021-12-22 17:58 UTC, bdlukaa requested changes
`icons.dart` should be unchanged

2021-12-22 17:58 UTC, bdlukaa commented on lib/src/controls/form/text_box.dart
> +              : backgroundColor.basedOnLuminance().withOpacity(0.6),
nice catch

2021-12-22 18:05 UTC, WinXaito requested changes
The idea seems good to me, the styles are much better, example in image below.

Before:
![image](https://user-images.githubusercontent.com/8223773/147136017-02616c66-e0b0-48d9-8e55-026593ad19e3.png)

After:
![image](https://user-images.githubusercontent.com/8223773/147136054-199ddce1-fdd8-438f-aeaa-957b17bb5506.png)

Difference in TextBox:

![image](https://user-images.githubusercontent.com/8223773/147136179-30718e85-3843-41f4-8bd9-25aff8b606b6.png)

2021-12-22 18:05 UTC, WinXaito commented on lib/src/controls/inputs/checkbox.dart
>              : Colors.transparent,
equivalent to: `uncheckedIconColor: ButtonState.all(Colors.transparent),`

@bdlukaa I don't have W11 for confirm that ?

2021-12-22 18:05 UTC, WinXaito commented on lib/src/controls/inputs/toggle_switch.dart
> +              : style.brightness.isLight ? const Color(0xFF5A5A5A) : const Color(0xFFCCCCCC),
Make color customisable in `ToggleSwitchThemeData` or `ThemeData` depending on their use.

2021-12-22 22:15 UTC, WinXaito commented on lib/src/controls/inputs/buttons/button.dart
> +          left: 11.0, top: 5.0, right: 11.0, bottom: 6.0,)),
Don't forget reformat.

Ps: you can click on "Resolved" on previous issue to indicate that is finished.
For example, when I apply requested modification, I click resolve when I corrected (before commit). With that, I now where I am.

2021-12-23 11:46 UTC, Kapranov98 commented on lib/src/controls/inputs/toggle_switch.dart
> +            const SizedBox(width: 10.0),
Hmmm. The guidelines have a 13px margin, although the Windows UI Library uses 10px. 
```
<x:Double x:Key="ToggleSwitchPreContentMargin">10</x:Double>
<x:Double x:Key="ToggleSwitchPostContentMargin">10</x:Double>
```
![toggle](https://user-images.githubusercontent.com/4894671/147235711-ff7c6e06-e773-465f-81b8-87bee4534fc0.png)

2021-12-23 11:53 UTC, Kapranov98 commented
Made a few more color changes based on the guidelines. Also added the correct Disabled styles for ToggleSwitch and Checkbox.

I think it's worth discussing which colors should be transferred to ThemeData and which ones to ToggleSwitchThemeData (and similar ones).

P.S. I need some help adding colors to ToggleSwitchThemeData.

2021-12-23 12:00 UTC, Kapranov98 commented on lib/src/controls/inputs/checkbox.dart
>              : Colors.transparent,
![изображение](https://user-images.githubusercontent.com/4894671/147237601-a7d6c248-afa6-4d36-9df9-aa49297adce2.png)

2021-12-23 12:52 UTC, WinXaito commented on lib/src/controls/inputs/toggle_switch.dart
> +            const SizedBox(width: 10.0),
👍 Ok for me

2021-12-23 12:54 UTC, WinXaito commented on lib/src/controls/inputs/checkbox.dart
>              : Colors.transparent,
👍

2021-12-23 13:28 UTC, bdlukaa approved these changes

2021-12-23 13:28 UTC, bdlukaa commented on lib/src/controls/inputs/checkbox.dart
> +            ? Colors.transparent
`uncheckedIconColor: ButtonState.all(Colors.transparent)` would be better

2021-12-23 15:00 UTC, WinXaito approved these changes

2021-12-23 15:01 UTC, WinXaito commented
@bdlukaa maybe need changelog update ?

2021-12-24 14:35 UTC, bdlukaa approved these changes
LGTM

2021-12-24 14:35 UTC, merged