WIP: Fix tabview
bdlukaa/fluent_ui pull request #119
Opened 2021-12-24 14:31 UTC by WinXaito

## Pre-launch Checklist

- [ ] I have run `dartfmt` on all changed files  
- [ ] I have updated `CHANGELOG.md` with my changes  
- [ ] I have run "optimize/organize imports" on all changed files
- [ ] I have addressed all analyzer warnings as best I could
- [ ] I have added/updated relevant documentation
- [ ] I have run `flutter pub publish --dry-run` and addressed any warnings

**WORK IN PROGRESS, DO NOT MERGE**

2021-12-24 15:56 UTC, WinXaito commented
There is one bug that I can't correct.

When the tabview is in a scrollable widget, the horitontal scroll on tabs doesn't prevent parent scroll. 

I searched a long moment for that and found nothing that work. So I added a parameter `wheelScroll` for enable or disable the wheel scroll on tabs (by default disabled).

2021-12-24 18:32 UTC, bdlukaa requested changes

2021-12-24 18:32 UTC, bdlukaa commented on lib/src/controls/navigation/tab_view.dart
> +  }
It'd be better to handle this in a `StatefulWidget`. Also, `scrollPosController` should be disposed

2021-12-24 18:32 UTC, bdlukaa commented on lib/src/controls/navigation/tab_view.dart
> +  late final ScrollPosController scrollPosController;
`scrollController` is a better name, no?

2021-12-24 18:32 UTC, bdlukaa commented on lib/src/controls/navigation/tab_view.dart
> +import 'package:scroll_pos/scroll_pos.dart';
`'package:scroll_pos/scroll_pos.dart'` should be exported

2021-12-24 18:32 UTC, bdlukaa commented on lib/src/controls/navigation/tab_view.dart
> +  /// larger of all items is bigger than screen width.
```suggestion
  /// The [ScrollPosController] used to move tabview to right and left when the
  /// tabs don't fit the available horizontal space.
  ///
  /// If null, a [ScrollPosController] is created internally.
```

2021-12-24 18:32 UTC, bdlukaa commented on lib/src/controls/navigation/tab_view.dart
> +  /// Indicate if the wheel scroll change the tabs positions.
```suggestion
  /// Indicate if the wheel scroll changes the tabs positions.
  ///
  /// Defaults to `false`
```

2021-12-24 18:32 UTC, bdlukaa commented on lib/src/controls/navigation/tab_view.dart
> +      onTertiaryTapUp: (_) => tabs[index].onClosed?.call(),
```suggestion
      onTertiaryTapUp: (_) => tab.onClosed?.call(),
```

2021-12-24 18:32 UTC, bdlukaa commented on CHANGELOG.md
> +- Fix scroll buttons when we have too many tabs in `TabView` ([#92](https://github.com/bdlukaa/fluent_ui/issues/92))
```suggestion
- Fix scroll buttons when there are too many tabs in `TabView` ([#92](https://github.com/bdlukaa/fluent_ui/issues/92))
```

2021-12-25 18:49 UTC, bdlukaa approved these changes

2021-12-25 18:49 UTC, merged