add context menu
bdlukaa/fluent_ui pull request #398
Opened 2022-06-18 06:40 UTC by nidetuzi

Add context menu

Add Tree View Right Click Item Event

I don't think I made the my menu well enough

## Pre-launch Checklist

- [ ] I have updated `CHANGELOG.md` with my changes  
- [x] I have run "dart format ." on the project  
- [ ] I have added/updated relevant documentation

2022-06-19 12:56 UTC, bdlukaa requested changes
`onRightClick` -> `onSecondaryTap`

2022-06-19 12:56 UTC, bdlukaa commented on lib/src/controls/navigation/tree_view.dart
> +  /// right click
Improve this documentation

```suggestion
  /// A tap with a secondary button has occurred.
```

2022-06-19 12:56 UTC, bdlukaa commented on lib/src/controls/navigation/tree_view.dart
> +              }
```suggestion
              widget.onRightClick?.call(item, details.globalPosition);
```

2022-06-19 12:56 UTC, bdlukaa commented on lib/src/controls/navigation/tree_view.dart
> +        ));
Trailing comma

```suggestion
        ),);
```

2022-06-19 12:56 UTC, bdlukaa commented on lib/src/utils/popup.dart
> +Future<T?> showMenu<T>({
Add documentation

2022-06-21 03:29 UTC, nidetuzi commented
I can't write comment, so I added a demo to it

2022-06-21 11:33 UTC, bdlukaa commented
conflicting files

2022-06-29 21:40 UTC, bdlukaa approved these changes

2022-06-29 21:40 UTC, merged