Fix tab view wheel scroll
bdlukaa/fluent_ui pull request #772
Opened 2023-03-15 19:47 UTC by WinXaito

## Pre-launch Checklist

- [ ] I have updated `CHANGELOG.md` with my changes  
- [ ] I have run "dart format ." on the project  
- [ ] I have added/updated relevant documentation

2023-03-17 19:36 UTC, bdlukaa commented
The `wheelScroll` property can then be removed, right?

2023-03-17 21:57 UTC, WinXaito commented
> The `wheelScroll` property can then be removed, right?

Note necessary, if a user want to keep the vertical scroll over all page he can. 

But I think we must put the default value to true. 

What do you think about that ? And if you really want to remove it, I think it’s preferable to set it to true by default and mark as deprecated to avoid a breaking change.

2023-03-18 21:26 UTC, bdlukaa commented
> And if you really want to remove it, I think it’s preferable to set it to true by default and mark as deprecated to avoid a breaking change and remove it in v5.0.0

Sounds fine to me! I checked on native and it stops the vertical scrolling, so I think we should do the same.

2023-03-20 21:30 UTC, bdlukaa requested changes
Tests are failing because we make use of the property on the example app

2023-03-20 21:30 UTC, bdlukaa commented on lib/src/controls/navigation/tab_view.dart
> +    @Deprecated('this value is no longer used and will be removed in the next major release.')
```suggestion
    @Deprecated('This property is no longer used and will be removed in the next major release.')
```

2023-03-20 22:20 UTC, WinXaito commented
👍 that must be good now

2023-03-22 19:16 UTC, bdlukaa approved these changes

2023-03-22 19:17 UTC, merged