Fixes leading/trailing widgets not centered in listTile
bdlukaa/fluent_ui pull request #940
Opened 2023-10-06 11:01 UTC by milindgoel15

This PR fixes the leading/trailing widgets alignment on cross axis. As of now, it was aligning items on `CrossAxisAlignment.start`. Hence, the PR addresses that and introduces 2 new parameters named `itemsAlignment` & `itemsPadding`. The first defaults to `CrossAxisAlignment.center` and second defaults to `kDefaultListTilePadding`.

Closes https://github.com/bdlukaa/fluent_ui/issues/939

## Pre-launch Checklist

- [X] I have updated `CHANGELOG.md` with my changes  
- [X] I have run "dart format ." on the project  
- [X] I have added/updated relevant documentation

2023-10-06 14:54 UTC, bdlukaa commented
Thanks for the PR! I'd rename both properties to `contentAlignment` and `contentPadding`. What do you think?

2023-10-06 15:07 UTC, milindgoel15 commented
Yep, sounds better.

Will do in a minute.

2023-10-07 13:02 UTC, bdlukaa requested changes

2023-10-07 13:02 UTC, bdlukaa commented on CHANGELOG.md
> +* add: added `itemsPadding` to listTile constructor (defaults to `kDefaultListTilePadding`)
```suggestion
  + added `contentAlignment` to `ListTile`
* Added `contentPadding` to `ListTile`
```

2023-10-07 13:02 UTC, bdlukaa approved these changes

2023-10-07 13:09 UTC, merged